### PR TITLE
Feature/python env

### PR DESCRIPTION
**Pull request by avecc003**
- Created project folder structure according to https://fastapi.tiangolo.com/tutorial/
- Created a requirements.txt in backend folder for other engineers to be able to pip install
- Added a backend folder for project cleanliness.

### CODE REVIEW

**Comment by ryanRATM** [comment]
@avecc003 looks like a good start! just two tiny things!
have a question regarding the requirements.txt file. how did you come up with the list of packages required to install?
small note on documentation if you don't mind adding a readme to the backend folder to give some context or maybe just shows the command line how to run.

**Comment by avecc003** [comment]
requirements.txt is automatically generated by pip, and is used for different developers to download the dependencies.
I will add the readme with the commands as soon as I can.

**Comment by khodizoda** [comment]
Looks good! My only question is packages in `requirements.txt`. Did you install any other dependencies apart from `fastapi` and `starlette`?

**Review by khodizoda — APPROVED** [review]
LGTM, thanks for fixing `requirements.txt`

**Pull request merged**
